baseURL = 'https://jackhale98.github.io/'
languageCode = 'en-us'
title = 'Your Blog Name'
theme = 'PaperMod'
paginate = 5

[params]
  description = 'Long-form tech writing and think pieces'
  author = 'Your Name'

  # Theme settings
  defaultTheme = 'auto'  # auto, light, dark
  disableThemeToggle = false

  # Post display settings
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  # Home page settings
  [params.homeInfoParams]
    Title = 'Welcome to My Blog'
    Content = 'Technology insights and long-form analysis'

  # Social icons
  [[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/'

  [[params.socialIcons]]
    name = 'twitter'
    url = 'https://twitter.com/'

  # Cover image settings
  [params.cover]
    hidden = false
    hiddenInList = false
    hiddenInSingle = false
    responsiveImages = true

  # Edit post link
  [params.editPost]
    URL = 'https://github.com/jackhale98/jackhale98.github.io/tree/main/content'
    Text = 'Suggest Changes'
    appendFilePath = true

[menu]
  [[menu.main]]
    name = 'Archive'
    url = '/posts/'
    weight = 10
  [[menu.main]]
    name = 'Search'
    url = '/search/'
    weight = 15
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 20

# Search settings
[outputs]
  home = ['HTML', 'RSS', 'JSON']
